name: Prerelease Workflow

on:
  push:
    branches:
      - beta
  workflow_dispatch:  # Ermöglicht manuelle Auslöser

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Semantic Release (Versioning)
        run: yarn release --dry-run --npm.skipChecks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: versioning  # Stellt sicher, dass die Versionierung abgeschlossen ist
    if: github.event_name == 'workflow_dispatch'  # Führt diesen Job nur bei manuellem Auslöser aus
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Publish to NPM
        run: yarn release --npm.skipChecks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
